version: '3.7'

services:
  # =wrapper
  wrapper:
    image: "sindriainc/xdev:${XDEV_TAG}"
    #image: "<private-image>"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
    #user: sindria
    environment:
        - XDEV_SINDRIA_USER_PASSWORD=${XDEV_SINDRIA_USER_PASSWORD}
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_DOCKER_GROUP_UID=${HOST_DOCKER_GROUP_UID}
        - DISPLAY=${XDEV_DISPLAY}
        - XDEV_MODE=${XDEV_MODE}
        - XDEV_WEB_PORT=${XDEV_WEB_PORT}
        - XDEV_VNC_HOST=${XDEV_VNC_HOST}
        - XDEV_VNC_PORT=${XDEV_VNC_PORT}
        - TZ=${TIMEZONE}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    hostname: "${APP_NAME}.local"
    ports:
      - "8080:8080"
    #network_mode: "host"
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    networks:
      default:
        ipv4_address: "${XDEV_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #devices:
    #  - "/dev/snd"

# =networks
networks:
  default:
    name: "vpc_xdev"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_xdev:
#    external: true