version: '3.7'

services:
  # =agent
  agent:
    image: "sindriainc/xdev:${XDEV_TAG}"
    container_name: "${APP_NAME}"
    restart: always
    command: tail -f /dev/null
    entrypoint: tail -f /dev/null
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${BASE_PATH}:${XDEV_AGENT_WORKING_DIR}"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8080:8080"
    #network_mode: "host"
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    networks:
      default:
        ipv4_address: "${XDEV_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #devices:
    #  - "/dev/snd"

# =networks
networks:
  default:
    name: "vpc_xdev"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}