version: '3.7'

services:
  # =xdev
  xdev:
    image: "sindriainc/xdev:${XDEV_TAG}"
    #image: "<private-image>"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
    #user: sindria
    working_dir: ${XDEV_WORKING_DIR}
    environment:
        - XDEV_SINDRIA_USER_PASSWORD=${XDEV_SINDRIA_USER_PASSWORD}
        - HOST_USER_UID=${HOST_USER_UID}  
        - HOST_DOCKER_GROUP_UID=${HOST_DOCKER_GROUP_UID}
        - DISPLAY=${XDEV_DISPLAY}
        - XDEV_MODE=${XDEV_MODE}
        - XDEV_WEB_PORT=${XDEV_WEB_PORT}
        - TZ=${TIMEZONE}
    volumes:
      # System volumes      
      - "/dev/shm:/dev/shm"
      #- "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/snd:/dev/snd" 
      - "/dev/dri:/dev/dri"
      - "/run/user/${HOST_USER_UID}/pulse:/run/pulse:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Config volumes
      #- "${APP_CONFIG_PATH}/xdev:/home/sindria/config"
      # Working volumes  
      - "projects:/home/sindria/Projects" 
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8080:8080"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    #networks:
    #  default:
    #    ipv4_address: "${XDEV_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"
    #devices:
    #  - "/dev/snd"

# =networks
#networks:
#  default:
#    name: "vpc_xdev"
#    driver: bridge
#    ipam:
#      config:
#        - subnet: ${NETWORK_SUBNET}

# =volumes
volumes:
  projects:
