name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: bash build.sh sindriainc/xdev 2.4.0

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login into registry
        run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Push Image
        run: docker push ${DOCKERHUB_NAMESPACE}/xdev:2.4.0
