name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build Image
      run: bash build.sh ${DOCKERHUB_NAMESPACE}/xdev ${RELEASE_VERSION}
    - name: Login into registry
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Push Image
      run: docker push ${DOCKERHUB_NAMESPACE}/xdev:${RELEASE_VERSION}
    - name: Push Image
      run: docker push ${DOCKERHUB_NAMESPACE}/xdev:latest
